# Generated by Django 4.2.7 on 2025-09-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('hope', 'Hope'), ('service', 'Service'), ('witness', 'Witness'), ('faith', 'Faith'), ('love', 'Love'), ('peace', 'Peace'), ('joy', 'Joy'), ('wisdom', 'Wisdom')], default='hope', max_length=20),
        ),
    ]
