# Generated by Django 4.2.7 on 2025-09-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_quote_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('medical', 'Medical & Mental Health Services'), ('water', 'Clean Water Access'), ('food', 'Food Security Programs'), ('spiritual', 'Spiritual & Community Services')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Image URL for the service')),
                ('features', models.JSONField(default=list, help_text='List of features/benefits')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Details',
                'ordering': ['order', 'title'],
            },
        ),
    ]
