# Generated by Django 4.2.7 on 2026-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('crusade', 'Crusade'), ('medical', 'Medical Outreach'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
