# Generated by Django 4.2.7 on 2026-02-26 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Leave blank if this is a general/other image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='frontend.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
