# Generated by Django 4.2.7 on 2026-03-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Total Attendance', 'New Converts'", max_length=100)),
                ('value', models.CharField(help_text="e.g. '184', '50+', or '14'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='frontend.event')),
            ],
            options={
                'verbose_name': 'Event Statistic',
                'verbose_name_plural': 'Event Statistics',
                'ordering': ['order', 'id'],
            },
        ),
    ]
