# Generated by Django 4.2.7 on 2026-03-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_eventstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeamMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '14', '4'", max_length=50)),
                ('label', models.CharField(help_text="e.g. 'Total Volunteers', 'Ministers'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_metrics', to='frontend.event')),
            ],
            options={
                'verbose_name': 'Team Metric',
                'verbose_name_plural': 'Team Metrics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Optimizing People'", max_length=100)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Lead Organization'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='frontend.event')),
            ],
            options={
                'verbose_name': 'Event Partner',
                'verbose_name_plural': 'Event Partners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
