# Generated by Django 4.2.7 on 2026-03-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_eventteammetric_eventpartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpartner',
            name='role',
        ),
    ]
