# Generated by Django 4.2.7 on 2026-03-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_eventpartner_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Spiritual Impact'", max_length=200)),
                ('items', models.TextField(help_text='Enter each achievement on a new line')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='frontend.event')),
            ],
            options={
                'verbose_name': 'Event Impact',
                'verbose_name_plural': 'Event Impacts',
                'ordering': ['order', 'id'],
            },
        ),
    ]
