# Generated by Django 4.2.7 on 2026-03-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_eventimpact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Belief',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
