# Generated by Django 4.2.7 on 2026-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_delete_activity_delete_belief_delete_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional end date for the event', null=True),
        ),
    ]
