# Generated by Django 4.2.7 on 2026-03-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_galleryimage_image_url_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this event from the public website'),
        ),
    ]
