# Generated by Django 4.2.7 on 2026-03-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_event_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Cloudinary or external photo URL (used instead of uploaded photo if set)'),
        ),
    ]
